---

inventory = /home/louis/ansible/inventory/hosts


- hosts: remoteservers
#  remote_user: ubuntu

  tasks:
    - name: install apt requirements
      become: yes
      become_method: sudo
      apt: 
          pkg=aptitude

    - name: update
      become: yes
      become_method: sudo
      apt:
          update_cache: yes

    - name: upgrade
      become: yes
      become_method: sudo
      apt:
          upgrade: yes
